### ISSUE TITLE
How to make work fieldcollection

### ISSUE THREAD

**Issue by Yivan** [w-vision/ImportDefinitions#10]
Hello,

I am trying to make your fieldcollection setter with no luck : (

First it seems there is a bug. You make a foreach by reference and update the reference inside the loop. It is dangerous from my experience and can lead to strange problem. Actually it leads to.
On this line https://github.com/w-vision/ImportDefinitions/blob/master/lib/ImportDefinitions/Model/Setter/Fieldcollection.php#L55 the problem dispear my making an `unset($key);` (so just after the loop). It is a good pratice.
If it is not done, making:
`foreach ($keys as $key) print_r($data[$key['from']]);`
send the same values... (and there was 2 differents values in the data). You can easily check it i think.

Second, I didn't manage to make it working:
Here is the field collection making of just two field: sku (input string) and stock (number).
Here is my csv exemple:
```
"sku1";"sku2";"stock1";"stock2"
"00001";"00002";88;99
```
sku1 and sku2 can be considered the primary.

I didn't get the point to configure the setter on the GUI... For "Keys" (from:to,from:to,from:to,...) I set:
`sku1:sku,sku2:sku` on both sku and stock in their config by choosing the "fieldcollection" setter. But how do I set that stock1 is linked to ref1 ?
Could you please give me some hints about please ?

Thanks a lot.

**Comment by dpfaffenbauer** [comment]
Maybe you didn't understand how the setter is designed to work. The problem with fieldcollections mainly is: they are 1:n relations. So you need to have a primary key to re-identify already added fieldcollections. For example:

**Address**

An address is identified using the city, street and country. So this is the primary key. In the setter-config, you need to specify which field from the field-collections maps to the import to identify already added field-collections.

In the address case, it would look like this:
```
csvCity:city,csvStreet:street,csvCountry:country
````

Unfortunately, this needs to be configured for every field mapping you make...

**Your use case**
You CSV has two sku''s and two stock-entries. Are they going to be 2 fieldcollections or one with 4 fields?

If 1: I don't think this is supported now... You would need to create an Interpreter for the fieldcollection field to make it work. Within the Interpreter you can write any code to prepare the data for pimcore.

It would work if the CSV looks like this:

```CSV
"sku","stock"
"00001",1
"00002",88
```

If 2: You Primary Key would look like this:
```
csvSku1:sku1,csvSku2:sku2
````

**Comment by Yivan** [comment]
Thanks a lot for your fast answer!

Yes it is going to be only 2 fieldcollections (each one have sku/stock field) and in csv it is sku1/stock1 and sku2/stock2.
So I will make my own setter.

For the unset problem I was talking here is an exemple:
[test.zip](https://github.com/w-vision/ImportDefinitions/files/531413/test.zip)
Without the unset it send back 88 - 88 wich is bad. With the unset it is good.
Same problem could occurs in: https://github.com/w-vision/ImportDefinitions/blob/master/lib/ImportDefinitions/Model/Setter/Fieldcollection.php#L87
Because no unset for this loop:
https://github.com/w-vision/ImportDefinitions/blob/master/lib/ImportDefinitions/Model/Setter/Fieldcollection.php#L47

Maybe I am wrong, but i want just tell you about this. I know using reference in loop is sometmes weird if you use the same key after. Making unset after the loop ensure no problem will occurs latter.

**Comment by Yivan** [comment]
From what i undestand your setter only import 1 item, not multiple item in field collections if we update the base object in the same time.
So for instance, if i import ecommerce orders (will be more simpler to explain on a classic use case), i need one CSV for the base data of the order object, and another CSV for the item of the order.

One line like this (base object + fieldcollection flatten):
```
"order number" (primary),"order date","sku1","item name 1"","sku2","item name2"
"ORD5412","2016-02-01 11:52:23","00001","Ipod","00002","Asus computer"
```
 **won't be possible with the current fieldcollection setter (skuX being the primary for fieldcollection) ?**

But:

CSV1 (for the order object):
```
"order number","order date"
"ORD5412","2016-02-01 11:52:23"
```
CSV2 (for the items fieldcollection of the order object)
```
"order number","sku","item name"
"ORD5412","00001","Ipod"
"ORD5412","00002","Asus computer"
```
**Is the way to go with 2 different importdefinition configs for the current fieldcollection setter ?**
The primary keys for field collection will be: `sku:sku` (csv name of the column:field name in the field collection). For composite primary key we can use "," to add others (like you said for city: csvCity:city,csvStreet:street,csvCountry:country).
**Am i right ?**

If yes maybe the documentation could be more precice on this point because i was thinking it create multipe items for the fieldcollection from the same CSV used to update the object.

Thanks again to take the time to explain me.

**Comment by dpfaffenbauer** [comment]
Well yes. The fieldcollection setter is not designed to allow multiple field-collections to be imported. As well as the UI doesn't really support it. You have to create your own Setter or Interpreter. 

If you could share your solution with us, that would be great :)

Regarding the unset Problem: I will find a solution for it and push it back to github.
