### ISSUE TITLE
File paths: relative to Pimcore root, relative outside Pimcore root, absolute

### ISSUE THREAD

**Issue by dkarlovi** [w-vision/ImportDefinitions#106]
The file path should be allowed to be outside Pimcore root just (as any other path) or absolute, currently it is expected to be strictly within, see https://github.com/w-vision/ImportDefinitions/pull/104/commits/739e57981f3f279f930af0b9ece5429fd82dde19#diff-2565629eedc3fd99c6a907528bb02eaaL132

**Comment by dpfaffenbauer** [comment]
not sure about that... Usually the web server does not have a lot of rights and cannot write outside. This is could also lead to security issues...

**Comment by dkarlovi** [comment]
Agreed, closing.
