### ISSUE TITLE
Rename Plugin to DataObjectDefinitions

### ISSUE THREAD

**Issue by dpfaffenbauer** [w-vision/ImportDefinitions#109]

**Comment by dkarlovi** [comment]
The key part is not definitions, it's the data. Maybe "Data Flow" (as in, import / export)?

**Comment by dpfaffenbauer** [comment]
Definitions cause of the configuration file it generates. I am still down to rename it to `DataDefinitions` or `DataObjectDefinitions`.

I will also rename all Namespaces from `ImportDefinitionsBundle` to `Wvision\Bundle\DataObjectDefinitionsBundle`.

This will come with 3.0. 

The latest Release with ImportDefinitions will be 2.3, that will also trigger deprecation notices and also support Pimcore 6.
