### ISSUE TITLE
[UX][Exports] append a new mapping on double click, drag'n'drop to panel

### ISSUE THREAD

**Issue by dkarlovi** [w-vision/ImportDefinitions#110]
If you double-click on the item in the left panel, it only works if you have no items already mapped, but once you have one, it stops working.

The user assumed it stopped working completely,  tried to drag n drop, but not on the "Mapping", just on the right panel which also didn't work.

A good UX fix would be to allow both double-click in left panel and drag to right panel to just append the items.

**Comment by dpfaffenbauer** [comment]
closed in exports PR #91
