### ISSUE TITLE
[Export] XSLT for XML exporter

### ISSUE THREAD

**Issue by dkarlovi** [w-vision/ImportDefinitions#121]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Branch?          | master

Allow supplying a path (asset?) with an [XSLT](https://en.wikipedia.org/wiki/XSLT) file, allowing the (capable) user to produce any XML output instead of the exporter having dozens of options to support arbitrary XML.

**Comment by dkarlovi** [comment]
Definitely an asset you can upload and change, we're currently using this approach without the automation and it needs to allow for different templates which are end-user accesible.

**Comment by dpfaffenbauer** [comment]
ping @dkarlovi whats the status on this one?

**Comment by dkarlovi** [comment]
Implemented in #148.
