### ISSUE TITLE
[Export] warn the user about the asset file being renamed

### ISSUE THREAD

**Issue by dkarlovi** [w-vision/ImportDefinitions#124]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Branch?          | master

If the target asset file was renamed (because of collision), output the new file as a warning at export end.

**Comment by dpfaffenbauer** [comment]
Not necessary in my opinion. ExportDefinitions job is to export files, if the file already exists, we just overwrite it. done. We don't handle versions exports or anything like that.

**Comment by dkarlovi** [comment]
But we rename the asset? It's doesn't get overwritten, it's using _1, _2, etc.

**Comment by dpfaffenbauer** [comment]
true, but only for artifacts.

**Comment by dkarlovi** [comment]
Well, that's my issue: in that case, issue a one-liner warning telling the user it happened?

**Comment by dpfaffenbauer** [comment]
but telling him where?

IMO: We should not even create a new file, we should just overwrite the existing one, if there is one.

**Comment by dkarlovi** [comment]
In the output log?

> Output to `var/assets/foo/bar.csv` requested, changed to `var/assets/foo/bar_2.csv` due to collision.

Or something.
