### ISSUE TITLE
Export configuration for fieldcollection not working

### ISSUE THREAD

**Issue by psuhane** [w-vision/ImportDefinitions#141]
| Q                | A
| ---------------- | -----
| Bug report?      | yes

- Export configuration for fieldcollection not working. 
- Not able to drag and drop fieldcollection's field in mapping panel. It only works on double click on collection's field.
- Edit option in context menu doesn't work for fieldcollection's fields.
- And at last while executing export command on console giving following error

**Attempted to call an undefined method named "getSetterConfig" of class "ImportDefinitionsBundle\Model\ExportMapping".  
  Did you mean to call e.g. "getGetterConfig" or "setGetterConfig"?**

**Comment by psuhane** [comment]
fieldcollection's field.

**Comment by dpfaffenbauer** [comment]
just pushed a fix, can you update and try again pls?

**Comment by psuhane** [comment]
Earlier I was able to save the export config without fieldcollection. But now following error is coming

fetcherConfig: This value is not valid.

**Comment by dpfaffenbauer** [comment]
can you give me your config? or give me some details pls.

**Comment by psuhane** [comment]
I am not able to save new export config also. Following is my exiting config export

{
   "fetcher":"objects",
   "fetcherConfig":{
      "unpublished":false
   },
   "fetchUnpublished":false,
   "name":"imp1",
   "provider":"csv",
   "class":"Test",
   "configuration":{
      "csvExample":null,
      "delimiter":",",
      "enclosure":"\"",
      "csvHeaders":null
   },
   "mapping":[
      {
         "getter":null,
         "getterConfig":null,
         "fromColumn":"name",
         "toColumn":"name",
         "interpreter":null,
         "interpreterConfig":null
      },
      {
         "getter":null,
         "getterConfig":null,
         "fromColumn":"description",
         "toColumn":"description",
         "interpreter":null,
         "interpreterConfig":null
      },
      {
         "getter":"fieldcollection",
         "getterConfig":{
            "field":null,
            "class":null,
            "keys":null
         },
         "fromColumn":"fieldcollection~collection~TestCollection~field1",
         "toColumn":"fieldcollection~collection~TestCollection~field1",
         "interpreter":null,
         "interpreterConfig":null
      }
   ],
   "runner":null,
   "stopOnException":false,
   "failureNotificationDocument":null,
   "successNotificationDocument":null
}

**Comment by dpfaffenbauer** [comment]
well, get rid of that and try again pls. There is already something messed up

**Comment by dpfaffenbauer** [comment]
closed due to inactivity.
