### ISSUE TITLE
Can't import Date field

### ISSUE THREAD

**Issue by amarjeet6694** [w-vision/ImportDefinitions#143]
**Unable to import Date field through CSV**

Following error occurs
**ERROR**     [import_definition] Error: Call to a member function getTimestamp() on string in /vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Date.php:76

**Possible Solution**
Need to convert date field in csv to \Carbon\Carbon type beforehand. Maybe create a new Interpreter for the same which does the above.

**Comment by dpfaffenbauer** [comment]
You can create the interpreter yourself or use the expression interpreter.
