### ISSUE TITLE
Interpret lists of relation and directly link them to related objects

### ISSUE THREAD

**Issue by Sonja-Schubert** [w-vision/ImportDefinitions#144]
| Q                | A
| ---------------- | -----
| Feature request? | yes
| Branch?          | 2.1

Hi There,
I'm currently trying to import a csv file like this:
key,name,relation
Specialkeyname,Product 1,Categoryname1;Categorytitle 2

Is it possible to resolve and directly link the categories during the product import? I tried to configure the relation column as iterator and inside as object_resolver with matching field title which did not work (Error: IteratorInterpreter can only be used with array values) I also tried to use the object resolver directly but this did not work either (Error: Call to undefined static method getByTitle in class DataObject\Concrete)

So my questions are:
- is there a possibility to interpret splitted lists inside an interpreter?
- is there a possibility to create relations to objects by the title field of the related object?

If yes a Hint would be great, if no it is a feature request ;-)

Kind regards,
Sonja

**Comment by dpfaffenbauer** [comment]
Use nested:

 - expression with value: [data.categoryname1, data.categoryname2]
 - iterator
 - object_resolver

Let me know if that works

**Comment by dpfaffenbauer** [comment]
what did you actually put in for the expression?

**Comment by dpfaffenbauer** [comment]
closed due to inactivity.
