### ISSUE TITLE
XML definition error

### ISSUE THREAD

**Issue by riky973** [w-vision/ImportDefinitions#145]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Branch?          | master
Hi all,
I’m new to Pimcore and I’m trying to define new xml import with ImportDefinitions plugin.
Settings defined as shown.
![image](https://user-images.githubusercontent.com/47085319/51838465-9f3f1c00-2306-11e9-808d-052b14804ed1.png)
XPATH defined as : /PRODUCTINFORMATION/PRODUCTS/PRODUCT
Example Xpath is the same
Example file is: 
		<PRODUCTINFORMATION>
		  <SUPPLIER>Mid Ocean Brands</SUPPLIER>
		  <DATE>20190122</DATE>
		  <TIME>03:00:27</TIME>
		  <LANGUAGE>IT</LANGUAGE>
		  <PRODUCTS>
			<PRODUCT>
			  <PRODUCT_NUMBER>AR1249-16</PRODUCT_NUMBER>
			  <PRODUCT_BASE_NUMBER>AR1249</PRODUCT_BASE_NUMBER>
			  <PRODUCT_ID>10134325</PRODUCT_ID>
			  <PRODUCT_PRINT_ID>40000011</PRODUCT_PRINT_ID>
			  <PRODUCT_NAME>TARGET</PRODUCT_NAME>
			  <PLCSTATUS>COLLECTION</PLCSTATUS>
			  <SHORT_DESCRIPTION>Bussola nautica</SHORT_DESCRIPTION>
			  <LONG_DESCRIPTION>Bussola nautica in alluminio in confezione di latta.</LONG_DESCRIPTION>
			  <DIMENSIONS>10,5X8X2 CM</DIMENSIONS>
			  <NET_WEIGHT>0,103</NET_WEIGHT>
			  <GROSS_WEIGHT>0,133</GROSS_WEIGHT>
			  <GROSS_WEIGHT_UNIT>KG</GROSS_WEIGHT_UNIT>
			  <COLOR_CODE>16</COLOR_CODE>
			  <COLOR_DESCRIPTION>argento opaco</COLOR_DESCRIPTION>
			  <MATERIAL_TYPE>Metal</MATERIAL_TYPE>
			  <CATEGORY_CODE>MOBL&amp;G_SRVCOP</CATEGORY_CODE>
			  <CATEGORY_LEVEL_1>MIDOCEANBRANDS</CATEGORY_LEVEL_1>
			  <CATEGORY_LEVEL_2>TEMPO LIBERO</CATEGORY_LEVEL_2>
			  <CATEGORY_LEVEL_3>SOPRAVVIVENZA</CATEGORY_LEVEL_3>
			  <CATEGORY_LEVEL_4>BUSSOLA</CATEGORY_LEVEL_4>
			  <IMAGE_URL>http://xxx.com/image/AR1249_16.jpg</IMAGE_URL>
			  <THUMBNAIL_URL>http://xxx.com/thumb/th_AR1249_16.jpg</THUMBNAIL_URL>
			  <COMMODITY_CODE>9014 1000</COMMODITY_CODE>
			  <COUNTRY_OF_ORIGIN>CN</COUNTRY_OF_ORIGIN>
			  <PACKAGING_CARTON>
				<LENGTH>0,560</LENGTH>
				<WIDTH>0,265</WIDTH>
				<HEIGHT>0,215</HEIGHT>
				<SIZE_UNIT>M</SIZE_UNIT>
				<WEIGHT>13,347</WEIGHT>
				<WEIGHT_UNIT>KG</WEIGHT_UNIT>
				<VOLUME>0,032</VOLUME>
				<VOLUME_UNIT>M3</VOLUME_UNIT>
				<INNER_CARTON_QUANTITY>10</INNER_CARTON_QUANTITY>
				<CARTON_QUANTITY>100</CARTON_QUANTITY>
			  </PACKAGING_CARTON>
			</PRODUCT>
		  </PRODUCTS>
		  </PRODUCTINFORMATION>

No colums shown in Mapping folder and an error is raised at savings.
Timestamp: Sun Jan 27 2019 17:51:47 GMT+0100 (Ora standard dell’Europa centrale) Status: 500 | Internal Server Error URL: /admin/import_definitions/definitions/get-columns Method: GET Message: Call to a member function getData() on null Trace: #0 /pimcore/cipi/vendor/w-vision/import-definitions/src/ImportDefinitionsBundle/Controller/ImportDefinitionController.php(91): ImportDefinitionsBundle\Provider\XmlProvider->getColumns(Array) #1 /pimcore/cipi/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): ImportDefinitionsBundle\Controller\ImportDefinitionController->getColumnsAction(Object(Symfony\Component\HttpFoundation\Request)) #2 /pimcore/cipi/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #3 /pimcore/cipi/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /pimcore/cipi/web/app.php(42): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #5 {main}
Can someone help me?

**Comment by dpfaffenbauer** [comment]
guess we solve this on the pimcore forum?
