### ISSUE TITLE
Problem Import fieldcollection from CSV FILE

### ISSUE THREAD

**Issue by antocipi** [w-vision/ImportDefinitions#147]
Hi,

I have create a DATA OBJECT FIELD-COLLECTIONS called **POSTEC** with 4 DATA COMPONENT :

1. Position ( Type: Many to One Relation)
2. AREA     ( Type: INPUT)
3. and others. ........

then i create a CLASS called Product with:

1. Layout and some data components
2. Layout ->Data Components (FIELD-COLLECTION) called **POSTECNOL** with SPECIFIC SETTING 
       ALLOW TYPES: POSTEC ( OBJECT CREATED BEFORE)

i want import data from COLUMN CALLED "0501_ImprintSize_IL1_T1" of file CSV to "AREA" (TYPE INPUT) of object POSTEC.

I 'm using ImportDefinitions and this setting in TAB "MAPPING"

FROM TO: **0501_ImprintSize_IL1_T1 ( COLUMN FILE CSV)**
TO: **AREA** (FIELD OF OBJECT FIELD-COLLECTIONS
INTERPRETER:  EMPTY ( THERE ISN'T CHOICE " FIELDCOLLECTION" how show in README GUIDE )
SETTER:  **fieldcollection**

SETTER SETTING

FIELD: **POSTECNOL**
KEYS (FROM: TO:) : **AREA:0501_ImprintSize_IL1_T1**

L'import show me in file this ERROR:

Error: Too few arguments to function Pimcore\Model\DataObject\AbstractObject::get(), 0 passed in /pimcore/cipi/vendor/w-vision/import-definitions/src/ImportDefinitionsBundle/Setter/FieldCollectionSetter.php on line 55 and at least 1 expected [] []

Because ? i have follow guide carefully.

Where i wrong ?

Let me know and thanks in advance.

Best Regards
Antonello

**Comment by antocipi** [comment]
PHOTO PROBLEM:

![object-fieldcollections](https://user-images.githubusercontent.com/44843689/52350249-626ed580-2a28-11e9-8dd8-962ec97a92b6.png)
![class](https://user-images.githubusercontent.com/44843689/52350251-63a00280-2a28-11e9-8ad4-77e2009860f9.png)
![mapping](https://user-images.githubusercontent.com/44843689/52350226-55ea7d00-2a28-11e9-8896-14944a8b90cc.png)
![setting-import](https://user-images.githubusercontent.com/44843689/52350254-64d12f80-2a28-11e9-9b5d-5d3af0d1776a.png)

**Comment by dpfaffenbauer** [comment]
please use the pimcore forum for support.
