### ISSUE TITLE
Maintenance Fails

### ISSUE THREAD

**Issue by josh-palan** [w-vision/ImportDefinitions#15]
When running maintenance, I get the following error:

Deprecated: call_user_func_array() expects parameter 1 to be a valid callback, non-static method ImportDefinitions\Maintenance::cleanupLogFiles() should not be called statically in /var/www/html/pimcore/models/Schedule/Maintenance/Job.php on line 69

Making the cleanupLogFiles function static resolves the error.

**Comment by dpfaffenbauer** [comment]
Pull Requests are always welcome ;)
