### ISSUE TITLE
Mapping tab empty

### ISSUE THREAD

**Issue by wpeisert** [w-vision/ImportDefinitions#159]
After saving the mapping the screen with rows is empty, the next edit in mapping is not possible. This issue is repetitive. Also the mapping for some rows is not possible (without logout-login) because the roll-offer is not showing. This problem make the work with import definition really uncomfortable.

| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Branch?          | master

**Comment by dpfaffenbauer** [comment]
Any step to reproduce? I don't have those issues

**Comment by wpeisert** [comment]
I try to get it. In my case it is not so reproducible.

**Comment by dpfaffenbauer** [comment]
ok, please reopen when you have a reproducable case. I can't do anything without knowing why its not working for you
