### ISSUE TITLE
[Bug] duplicate path not counted as an import error

### ISSUE THREAD

**Issue by dkarlovi** [w-vision/ImportDefinitions#163]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Branch?          | master

We have an import which results in a duplicate path, but checking the error count gives

```
Total lines processed: 12
Updates: 12
Errors count: 0
```

It seems an duplicate path should also be counted as an error.

**Comment by dpfaffenbauer** [comment]
sure? Doesn't ImportDefinitions check for it and generates a unique path then?

**Comment by dkarlovi** [comment]
Need to check, but I think this applies for data objects.

**Comment by dpfaffenbauer** [comment]
https://github.com/w-vision/ImportDefinitions/blob/master/src/ImportDefinitionsBundle/Importer/Importer.php#L509

There it is, it always gets a unique key if the path is the same. I don't count a duplicate path as an error if you use the configuration for path. If you have your own interpreter for key/path, you have to handle that yourself. But, I think we can add some better error handling here.

**Comment by dpfaffenbauer** [comment]
closed for not having any activity in about a year now... If still needed, let me know.
