### ISSUE TITLE
Can you possibly create a tutorial video, from the basics?

### ISSUE THREAD

**Issue by szfine** [w-vision/ImportDefinitions#17]
Hi there,

I was hoping you wouldn't mind creating video tutorial?
Where you run through all the different steps to getting a parsed XML file into a product feed.

If you just turn on a screen recorder and go through the steps, that would be awesome.

Thank you!

**Comment by dpfaffenbauer** [comment]
Hi there,

sorry, I can't make that. I don't really have time for that. 

But basically: It's very easy to use. But XML is a very difficult format, cause of its hierarchy. CSV would be much easier.

Regards
Dominik
