### ISSUE TITLE
 [ERROR] Bundle ImportDefinitionsBundle can not be installed                                                            

### ISSUE THREAD

**Issue by gicuturetchi** [w-vision/ImportDefinitions#182]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Branch?          | master

When I tried to install the ImportDefinitionBundle I get this error : 
```
 [ERROR] Bundle ImportDefinitionsBundle can not be installed                                                            
```
The problem appear when I tried to do : 
```
bin/console pimcore:bundle:install ImportDefinitionsBundle
```

When I tried this command : 
```
bin/console import-definitions:list
```
I get the error : 
```
  Class ImportDefinitionsBundle\Model\ImportDefinition has no getList function and thus is not supported here  
```
Please help me.

**Comment by dpfaffenbauer** [comment]
This has already been fixed. That was a bug in CoreShop. If you have installed CoreShop, try updating it to the latest dev version.

**Comment by gicuturetchi** [comment]
@dpfaffenbauer How I can do it please ?
