### ISSUE TITLE
Provider is not taken into account

### ISSUE THREAD

**Issue by gicuturetchi** [w-vision/ImportDefinitions#183]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Branch?          | master

Hello guys, I tried to use this plugin. So my config is :
![Screenshot from 2019-06-03 12-16-05](https://user-images.githubusercontent.com/6445778/58790668-84085400-85f9-11e9-904b-74a610b91b03.png)

But I get an 500 eror
![Screenshot from 2019-06-03 12-18-01](https://user-images.githubusercontent.com/6445778/58790750-a69a6d00-85f9-11e9-8527-d586f76827a7.png)

Any ideas ?

**Comment by dpfaffenbauer** [comment]
No idea, sorry. I use this plugin every day and never had that issue.
