### ISSUE TITLE
After changing provider configuration mapping stays in config files

### ISSUE THREAD

**Issue by kubaplas** [w-vision/ImportDefinitions#190]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Branch?          | master

How to reproduce:

1. Create a definition with CSV provider. Paste in sample CSV headers. Map the columns to the fields on the Mapping tab. Save the definition.
2. Change provider configuration by removing some columns from the sample CSV file. Save the definition.
3. Columns mapped in the previous version of provider config are still present in the config file.

Now running the import will use mappings that are present in the config file, but not in GUI and most importantly not in the CSV file!
This causes writing empty values to objects, because there is no column in the CSV file corresponding to hanging mapping from config file.

Proposed solution:
1. Saving definition should remove non-mapped columns from config file.
2. If the input import file doesn't have a column that is mapped in ID, this field should be skipped instead of using empty/null as a source data.

**Comment by kubaplas** [comment]
@dpfaffenbauer I think this issue can now be closed.

**Comment by dpfaffenbauer** [comment]
:) sure thanks
