### ISSUE TITLE
ImportDefinitions does not ignore non-mandatory fields

### ISSUE THREAD

**Issue by Cruiser13** [w-vision/ImportDefinitions#2]
I'm trying to import a CSV as objects using the importer. One of the object fields is missing in the CSV.
It's a number field with the following settings:
`
					{
						"fieldtype":"numeric",
						"width":"",
						"defaultValue":null,
						"queryColumnType":"double",
						"columnType":"double",
						"phpdocType":"float",
						"integer":true,
						"unsigned":true,
						"minValue":1,
						"maxValue":99999,
						"decimalPrecision":null,
						"name":"postal",
						"title":"Postleitzahl",
						"tooltip":"",
						"mandatory":false,
						"noteditable":false,
						"index":false,
						"locked":false,
						"style":"",
						"permissions":null,
						"datatype":"data",
						"relationType":false,
						"invisible":false,
						"visibleGridView":false,
						"visibleSearch":false
					},
`

Importer error message is "[Pimcore\Model\Element\ValidationException]  Value in field [ postal ] is not at least 1 fieldname=postal". 

The error itself is correct but I believe it should still import the data because the field postal is not mandatory and does not even exist in CSV.

**Comment by dpfaffenbauer** [comment]
hmm.... the importer doesn't take care of validation, because this is done by pimcore. Could you please provider more information? eg. Class Export and CSV?

**Comment by Cruiser13** [comment]
Looks like the issue is deeper within. CSV seems to need enclosure character which our CSV does not include:

`
ID;Anrede;Vorname;Nachname;Adresse;Telefon;Handy;E-Mail;Firma
`

It fails at Warning: fgetcsv(): enclosure must be a character in pimcore\plugins\ImportDefinitions\lib\ImportDefinitions\Model\Provider\Csv.php on line 149

So that does probably mess up the fields which does lead to the error above. Postal is filled with a wrong value I think.

**Comment by dpfaffenbauer** [comment]
thats fixed, could you please try it again?

**Comment by Cruiser13** [comment]
Thanks, I investigated further. Fixing the error by reformating CSV does not fix the error above. Postal field does still seem to be an issue. 

My current CSV:

`
"ID";"Anrede";"Vorname";"Nachname";"Adresse";"Telefon";"Handy";"E-Mail";"Firma"
`

My Importer settings are looking like this:
![importer](https://cloud.githubusercontent.com/assets/2771909/16589240/8eff499e-42d2-11e6-9be5-8b16f7be0cfe.png)

**Comment by Cruiser13** [comment]
Removing min and max value from the postal field does fix the issue. All other non-mandatory fields are being ignored properly. Looks like this is a pimcore issue with mandatory vs minimum values and not a plugin issue here. I'll push this to the main repository.

**Comment by dpfaffenbauer** [comment]
:thumbsup:

**Comment by dpfaffenbauer** [comment]
related to https://github.com/pimcore/pimcore/issues/722#issuecomment-230520061
