### ISSUE TITLE
Pimcore does not work after Update

### ISSUE THREAD

**Issue by aarongerig** [w-vision/ImportDefinitions#26]
After updating Pimcore from v4.4.1 to v4.4.3 and updating ImportsDefinitions, Pimcore does not work anymore. ImportsDefinitions Configs are not correctly showing up and after removing a custom runner from my startup.php file, pimcore now works.

![Screenshot of configs](https://cloud.githubusercontent.com/assets/17384333/23451443/3d1102d6-fe60-11e6-8279-a786489c9577.png)

**Comment by dpfaffenbauer** [comment]
Can't really reproduce your problem.... I'll just close this issue and if it happens again, we'll look closer at it, ok?
