### ISSUE TITLE
Custom provider creation

### ISSUE THREAD

**Issue by grazianodimaio** [w-vision/ImportDefinitions#27]
Good morning!

I saw you pimcore extension, and i need it badly for a project involving data import.

I need to create my custom provider because i need to find a way to import a fixed with file.

How can i do it ?

I'm trying to enable my custom provider, which are the steps to create it ?

Thank you!

Graziano

**Comment by dpfaffenbauer** [comment]
1. Create a Custom Plugin
2. Create a folder in your Plugin "CustomPlugin/lib/ImportDefinitions/Model/Provider
3. Create a File in this Folder "YourProvider.php"
4. The file should basically look like this:

```php
<?php

namespace ImportDefinitions\Model\Provider;

use ImportDefinitions\Model\AbstractProvider;
use ImportDefinitions\Model\Definition;
use ImportDefinitions\Model\Filter\AbstractFilter;
use ImportDefinitions\Model\Mapping\FromColumn;
use Pimcore\Model\Object\Concrete;

class YourProvider extends AbstractProvider
{
    //Check if data is valid
    public function testData()
    {
        return true;
    }
    
    //Get Columns from data, see CSV/JSON/XML for more details
    public function getColumns()
    {
        return ['col1', 'col2'];
    }

    //Parse your file here
    protected function getData($definition, $params, $filter = null)
    {
        $file = PIMCORE_DOCUMENT_ROOT . "/" . $params['file'];

        //TODO: Parse file
        return $data;
    }
}

```
5. Implement missing methods and your provider
6. Register your Provider in your Plugin.php:
```php
\ImportDefinitions\Model\AbstractProvider::addProvider('YourProvider');
```
