### ISSUE TITLE
Error: Document requires key, generated key automatically

### ISSUE THREAD

**Issue by grazianodimaio** [w-vision/ImportDefinitions#28]
Good Evening!

I have a problem importing the productCategory.

I'm using a simple CSV file composed like this:

> id;parent;codice_settore;settore
> 1;49;15;PESCHERIA
> 2;49;13;ORTOFRUTTA
> 3;49;1;BEVANDE
> 4;49;2;ALIMENTARI

the separator is ";".

In the mapping i made this modifications:

![screenshot 2017-04-21 19 41 42](https://cloud.githubusercontent.com/assets/5684998/25289601/90cdd86c-26ca-11e7-95cb-9b84a6e589c7.png)

Then, when i run the import the script tells me this

![screenshot 2017-04-21 19 42 49](https://cloud.githubusercontent.com/assets/5684998/25289642/c6684160-26ca-11e7-8351-6b98a94e5339.png)

Which field i have to select like primary ?

Thanks!

Graziano

**Comment by grazianodimaio** [comment]
In addition,

if i use a systemColumn, like the key as primary, i obtain this kind of error 

![screenshot 2017-04-21 19 53 53](https://cloud.githubusercontent.com/assets/5684998/25289985/44c71a4e-26cc-11e7-80f0-908e4f24aeb2.png)

**Comment by dpfaffenbauer** [comment]
Hi,

ImportDefinitions goal is to create and update existing objects. To identify existing Objects, we need to have some kind of identifier = primary identifier. Therefore you can check columns as primary in the mapping.

SystemColumns should work fine for keys as well, but it seems you found an issue there, I'll try to solve it asap, but I am very busy at the moment. Could you please try to use a different identifier?

**Comment by dpfaffenbauer** [comment]
Reopen once the issue reappears
