### ISSUE TITLE
Update existing objects. Not create new

### ISSUE THREAD

**Issue by alexdrupal** [w-vision/ImportDefinitions#31]
Hello

Thanks for your awesome work on this plug-in. I'm trying to create import definition to update price for existing objects (products).
Here is an example of my csv file

"model","price"
"ADN120X24","2345"
"ADN120X30","2345678"

My object has sku field which is not listed in csv. This is by design, I want just to be able to update prices of products by model number, not by the sku.
Is that possible with your plugin?

Let me know. Thanks!

**Comment by alexdrupal** [comment]
Attaching my import definition settings.
![import_definition1](https://user-images.githubusercontent.com/38625/28578725-3e122856-7163-11e7-9303-2ed3f4f70122.png)
![import_definition2](https://user-images.githubusercontent.com/38625/28578734-41b8e0a8-7163-11e7-81ea-003447039270.png)
![import_definition3](https://user-images.githubusercontent.com/38625/28578717-398a9804-7163-11e7-90dd-e0c9977c09a5.png)

**Comment by dpfaffenbauer** [comment]
- Is your model number unique? If so, your definition should work as expected.
- Are you sure your Model with regarding Numbers exist in your Database?
- If you don't want that ImportDefinitions creates new Objects, just enable the checkbox "Skip new Objects"

**Comment by alexdrupal** [comment]
Thanks. All working now.
