### ISSUE TITLE
Warning: include_once(ProcessManager/Model/Process.php)

### ISSUE THREAD

**Issue by alexdrupal** [w-vision/ImportDefinitions#32]
Hello

I'm trying to run my first Import definition profile and getting this error:
`Warning: include_once(ProcessManager/Model/Process.php)`
The include path is correct - it includes path to ImportDefinitions lib folder:
`/var/www/pimcore-live/plugins/ImportDefinitions/lib`, but there is no `ProcessManager/Model/Process.php` class in that folder. 

What am I missing?

**Comment by dpfaffenbauer** [comment]
should already been solved with this commit: https://github.com/w-vision/ImportDefinitions/commit/89f1d76fc7f28d7e6665afe1e188a598b246fcf0

try updating to "dev-master"

**Comment by dpfaffenbauer** [comment]
if problem still exists, please open a new issue
