### ISSUE TITLE
Alter/modify key field before import

### ISSUE THREAD

**Issue by alexdrupal** [w-vision/ImportDefinitions#34]
In my CSV I have the SKU field with values like: 1, 2, 3
In PIMCore I have SKU with values: prefix-1, prefix-2, prefix-3 so it actually prefix-[sku_from_csv]
So I want to be able to preprocess values from csv and append prefix to each sku value before search for objects in PIMCore.

I guess it is possible with your module. Please, push me in right direction.
Thanks!

**Comment by dpfaffenbauer** [comment]
No, unfortunately thats not possible. The Primary Identifier needs to be equal to your CSV File. So, if you have a Product with a SKU of 1, your CSV needs to delivery 1 as identifier.

If you are taking about the key in the object-tree, thats possible
 - Create an interpreter
 - Change setting of Key to prefix-%Text(SKU_CSV_FIELD_NAME);

**Comment by alexdrupal** [comment]
Thanks!
