### ISSUE TITLE
Run import  through CRON - get a list of unimported/error records 

### ISSUE THREAD

**Issue by alexdrupal** [w-vision/ImportDefinitions#36]
Hello

Is it possible to get a list of errors/unprocessed records during import process?
I writing small cron script and want to send an email to administrator when import process finishes with errors.

Possible?

**Comment by aarongerig** [comment]
Hi @alexdrupal,

> Is it possible to get a list of errors/unprocessed records during import process?

Yes, all data rows, which failed to import are being logged automatically.

> Admin Notification on Error/Success

Yes, also possible. Simply define some email documents (see screenshot below).

![email notification](https://user-images.githubusercontent.com/17384333/28913212-85c091bc-7837-11e7-8188-71f2dc1abb30.png)

Hope this helps.

**Comment by alexdrupal** [comment]
Thanks for the fast answer, but could you provide a screen-shot of Failure notification document settings?

**Comment by dpfaffenbauer** [comment]
Basically, its a standard pimcore mail document. Import-Definitions calls it with following parameters:
```
"exceptions", //All Thrown Exceptions
"objectIds" //Processed Object Ids,
"className" //Object Class Name,
"countObjects", //Count of processed Objects
"countExceptions", //Count of exceptions
"name", //Name of Definition
"provider" //Prodivder of Definition (sql, csv, xml, etc.)
```

Unfortunately, there is no array with failed or succeeded objects though. You can create a PR for that if you need it.
