### ISSUE TITLE
Can't import href: Error invalid href relation fieldname=xxx

### ISSUE THREAD

**Issue by antinoos** [w-vision/ImportDefinitions#37]
Hello,
We have an issue with the href import

We are trying to import a class GROUPS related with "href" to a class FAMILIES
We have tried many settings but we still have the same alert in logs when we execute the CLI import:

**Error invalid href relation fieldname=famille**

Our import file contains two columns with fields "groups" and "famille"
Can you tell us how settings should be (interpreters, setters, keys are not clear for us)
Our version: pimcore 4.6
A standard import is working well if in the column " famille"  we setup the import file with path like /Catalog/Famille/xxx

We would like to avoid "/Catalog/Famille/" string in the import as the Import should recognize xxx as a href without writing all the path. 
Best regards

Alexandre

**Comment by aarongerig** [comment]
Hi Alexandre

In order to be able to import data into a field of type `href` you have to choose the `Href` interpreter. This interpreter expects id's as value, as you can see [here](https://github.com/w-vision/ImportDefinitions/blob/master/lib/ImportDefinitions/Model/Interpreter/Href.php#L50).

Hope this helps!

Cheers,
Aaron

**Comment by dpfaffenbauer** [comment]
Short info on interpreters and setters:

***Setters***
are small helpers to set the right value into an object. For example: ObjectBrick: ObjectBricks are different to set then direct fields within an DataObject.
They are designed to be extendable, but usually, you don't need to. Just for special cases like: "OnlyApplyWhenNotEmpty".

***Interpreters***
Are kind of transformers if you prefer transformers better ;). They help you interpret/transform values before you store them into the DataObject. For example: Finding the correct relations for href/multihref fields, or Downloading Assets and store them into Pimcore.

**Comment by antinoos** [comment]
Thank you very much  for your answers. We tried again (I tried yesterday with IDs), but issue is still there

Here my settings

1. Class Group 
* name (input)
* famille (href with class Famille)

2. class Famille
* name (input)
* code (input)
* category (href with class Category)

3. Import definition settings to Import Groups
Path: /Catalog/Groups
key, Cleaner and all others are empty

4. Provider settings
CSV example : 
group, famille
LM31016, 1010

In a standard import we put /Catalog/Groups/1010 in "famille
Here, we put 1010 in the field 

Do you think there is something wrong here?
Alexandre

**Comment by fffab** [comment]
Hello,
we investigate with Alexandre on this issue, and we found something that could be usefull.

href interpreter needs an id, ok. before that the function check it the objectClass exists, and this point was in our case not fullfilled.

$objectClass that is passed to function is catalogFamille
it can't be loaded till the real name of the class is CatalogFamille
we find a workaround in trying to ucfirst to load the class by adding theses couples of lines to 

plugins/ImportDefinitions/lib/ImportDefinitions/Model/Interpreter/Href.php::interpret(L:45)

        if (!Tool::classExists($class))
        {
            $class = 'Pimcore\Model\Object\\' . ucfirst($objectClass);             
        }

thanks for helping us to solve our problem, but maybe such a change could be made to the plugin to help others

regards,

**Comment by fffab** [comment]
sorry, extra question
when importing large files (own interpreter now), sometimes i get "Segmentation fault"
have you any idea of what that could mean ?

Regards,
Fabrice

**Comment by dpfaffenbauer** [comment]
1. can you create a PR for the fix?

2. seg fault sounds not good at all and seems to be a PHP bug. What version are you using? Have you tried using a newer version? Have you tried increasing memory_limit?

**Comment by fffab** [comment]
1. done
2. memory_limit is 128M by now, php version is 7.0.19-1. I will investigate on this, but if you have any requirements list I would be pleased to read.
Regards,

**Comment by dpfaffenbauer** [comment]
There a actually no real requirements and we are using 7.0 as well. (Not sure now which version exactly).

Could you please investigate further and create a separate issue if it comes from ImportDefinitions?

**Comment by fffab** [comment]
i will. i have some other imports to create, if this reproduce we well open another issue.
