### ISSUE TITLE
Large classification store key definitions support

### ISSUE THREAD

**Issue by kubaplas** [w-vision/ImportDefinitions#41]
When dealing with classes which have a classification store field, plugin will try to load all key definitions from classification store.

On large stores this will cause timeouts on server side or make browser unresponsive.

Possible sollution: use mechanism similar to one used when adding cs field into standard Pimcore grid.

**Comment by dpfaffenbauer** [comment]
Where does this actually happen? Creating the FieldDefinition for ImportDefinitions Backend?

**Comment by kubaplas** [comment]
After opening Mapping tab, when class with classification store is selected in configuration.

**Comment by dpfaffenbauer** [comment]
Alright, I'll have a look at it and try to find a solution.

**Comment by dpfaffenbauer** [comment]
Just created a classification store with 1000 keys and didn't run into any problems. Could you provide me your classification store + pimcore class + import-definition config? so I can try to reproduce your issue.

**Comment by kubaplas** [comment]
Yeah, so my cs may be not optimised, but it has 27k of keys. I'll try to show it to you.

**Comment by dpfaffenbauer** [comment]
ping @kubaplas

**Comment by dpfaffenbauer** [comment]
closed due to inactivity.
