### ISSUE TITLE
Error in 'key' field usage

### ISSUE THREAD

**Issue by wpeisert** [w-vision/ImportDefinitions#43]
When I mark field 'key' as primary, erroneous SQL is generated.
Instead of 'o_key' field 'key' is used.

SELECT object_1.o_id as o_id, `object_1`.`o_type` FROM `object_1` WHERE (key = '489119900' AND  object_1.o_type IN ('variant','object','folder'));

Error: An exception occurred while executing 'SELECT object_1.o_id as o_id, `object_1`.`o_type` FROM `object_1` WHERE (key = ? AND  object_1.o_type IN ('variant','object','folder'))' with params ["4891199007996"]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key = '489119900' AND  object_1.o_type IN ('variant','object','folder'))' at line 1

**Comment by dpfaffenbauer** [comment]
are you using Version 1 or 2?

**Comment by dpfaffenbauer** [comment]
never mind, fixed it for both versions.
