### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Yivan** [w-vision/ImportDefinitions#44]
Installing with Pimcore 5.0.2 seems to lead to an error:

`Fatal error: Class CoreShop\Bundle\ResourceBundle\Pimcore\PimcoreRepository cannot implement previously implemented interface CoreShop\Component\Resource\Repository\RepositoryInterface in .../web/vendor/coreshop/resource-bundle/Pimcore/PimcoreRepository.php on line 21`

It seems there are some incompatibility between the 2 bundles for now.

**Comment by dpfaffenbauer** [comment]
Doesn't seem to happen to me, can you try running

```composer update --with-dependencies```

This should get you the latest version of coreshop libraries.

**Comment by Yivan** [comment]
Thanks for looking for it!

I tested by running `composer update --with-dependencies` but same error.

As i don't want to change the composer to dev minimal dependency to prevent some project breaks, I install each dependency like this:
```
composer require coreshop/registry ^2.0-dev@dev
composer require coreshop/resource ^2.0-dev@dev
composer require coreshop/resource-bundle ^2.0-dev@dev
composer require w-vision/import-definitions:^2.0-dev@dev
composer update --with-dependencies
```

After that, i add to AppKernel.php:

```
    $collection->addBundles(array(
        new \JMS\SerializerBundle\JMSSerializerBundle(),
        new \CoreShop\Bundle\ResourceBundle\CoreShopResourceBundle(),
        new \FOS\RestBundle\FOSRestBundle(),
        new \Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle(),
        new \Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle()
    ), 120);
```
And after I run:
bin/console pimcore:bundle:enable ImportDefinitionsBundle

And here come the error i give in my first post. Here a screen shoot (error is at the end, and it can be seen a warning json encoding in the middle of the process):

![warning](https://user-images.githubusercontent.com/9025839/32788300-2615462c-c959-11e7-8226-30cf8acd50dd.png)

Just if you need, running `composer update --with-dependencies` was ok:

![with-dep](https://user-images.githubusercontent.com/9025839/32788346-425dd984-c959-11e7-87b3-f3cacd96ae51.png)

**Comment by dpfaffenbauer** [comment]
can you please check your composer.lock file for what version of coreshop/resource-bundle is installed?

**Comment by Yivan** [comment]
Here you will find the composer.json and composer.lock:

[bug-composer.zip](https://github.com/w-vision/ImportDefinitions/files/1471494/bug-composer.zip)

**Comment by Yivan** [comment]
I can add that during composer require command, i get for:

`composer require coreshop/registry ^2.0-dev@dev => dev-master 5c6a991`

`composer require coreshop/resource ^2.0-dev@dev => dev-master 65fb90e`

```
composer require coreshop/resource-bundle ^2.0-dev@dev => see just below
  - Installing behat/transliterator (v1.2.0): Downloading (100%)
  - Installing gedmo/doctrine-extensions (v2.4.31): Downloading (100%)
  - Installing stof/doctrine-extensions-bundle (v1.2.2): Downloading (100%)       - Installing phpoption/phpoption (1.5.0): Downloading (100%)
  - Installing phpcollection/phpcollection (0.5.0): Downloading (100%)
  - Installing jms/parser-lib (1.0.0): Downloading (100%)
  - Installing jms/metadata (1.6.0): Downloading (100%)
  - Installing jms/serializer (1.9.1): Downloading (100%)
  - Installing jms/serializer-bundle (1.5.0): Downloading (100%)
  - Installing willdurand/jsonp-callback-validator (v1.1.0): Downloading (100%)   - Installing willdurand/negotiation (v2.3.1): Downloading (100%)
  - Installing friendsofsymfony/rest-bundle (2.2.0): Downloading (100%)
  - Installing doctrine/orm (v2.5.12): Downloading (100%)
  - Installing coreshop/resource-bundle (2.0.0-alpha.2): Downloading (100%) 
```

`composer require w-vision/import-definitions:^2.0-dev@dev => dev-master 04e30bf`

I hope it helps.

**Comment by dpfaffenbauer** [comment]
As I though, you are using an outdated version of resource-bundle. 

As you can se here: https://github.com/coreshop/ResourceBundle/commits/master/Pimcore/PimcoreRepository.php, I fixed that bug. (I did a lot more in that commit) on 23rd June.

The commit sha1 your composer.lock refers to is from 10th June. Actually it is this commit (https://github.com/coreshop/ResourceBundle/commit/fe7eeb6ff6ed7a4bc811363927932c7d5a90c180)

Can you try installing the actual alpha-3 of all of these libs?

**Comment by Yivan** [comment]
Just to give more information too:

- i have chown all the directory/subdirectory/files of the project for www-data, to prevent permission problem
- pimcore chache is cleared
- composer is runned with www-data user (`su -l www-data -s /bin/bash`)
- pimcore is 5.0.2 official stable, no other plugins/extension, nor specific development.

**Comment by Yivan** [comment]
I tried:

composer require coreshop/registry ^2.0.0-alpha.3@dev => nothing has been updated (already installed i think)
composer require coreshop/resource ^2.0.0-alpha.3@dev => nothing has been updated (already installed i think)

composer require coreshop/resource-bundle ^2.0.0-alpha.3@dev
Ouch this one seems to need all coreshop ?
`coreshop/resource-bundle 2.0.0-alpha.3 requires coreshop/pimcore ^2.0 -> satisfiable by coreshop/pimcore[2.0.0-alpha.3, 2.0.x-dev]`
**Should I install coreshop ? (i don't really want because just the import plug in is necessary in my case)**

**Comment by dpfaffenbauer** [comment]
coreshop/pimcore are in fact just some utilities someone could need. CoreShop uses it for migration purposes.

**Comment by Yivan** [comment]
Ok installating went great!

Now there is another problem :)

All static asset aren't loaded... for instance:
http://www.domain.com/bundles/importdefinitions/pimcore/js/startup.js send a 404
Same for all JS files form the plugin importdefinitions.

Looking on the file server, i got:
`/web/bundle/coreshopresource` (a symlink)
This symlink point to : `/vendor/coreshop/resource-bundle/Resources/public` wich contain just one directory `pimcore `-> `js `-> see tree here:

![folder](https://user-images.githubusercontent.com/9025839/32790933-0863695e-c960-11e7-8a8f-80a36a20d699.png)

**Comment by dpfaffenbauer** [comment]
please try

```bin/console assets:install```

**Comment by dpfaffenbauer** [comment]
Thats symfony, it copies the public resources into the web folder.

You can also symlink them by providing an argument --symlink (guess thats the symlink you saw).

I'll close this issue then.

**Comment by Yivan** [comment]
Tanks a lot @dpfaffenbauer for this fast support ! ; )

For future other user, maybe you could update the installation method, by giving another install option wich does not need to change minimal-stability for the all project.
Finally all went ok by running those, so maybe it could be added to install documentation:

```
composer require coreshop/registry ^2.0.0-alpha.3@dev
composer require coreshop/resource ^2.0.0-alpha.3@dev
composer require coreshop/pimcore ^2.0.0-alpha.3@dev => dev-master d4cb68c
composer require coreshop/resource-bundle ^2.0.0-alpha.3@dev
composer require w-vision/import-definitions:^2.0.0-alpha.3@dev
in/console assets:install
```

It could be removed when stable will be out.

**Comment by dpfaffenbauer** [comment]
the min-stability will be removed anyway as soon as 2.0 of coreshop will be released.
