### ISSUE TITLE
Extra fields in the mappig config

### ISSUE THREAD

**Issue by zavodyanka** [w-vision/ImportDefinitions#48]
**interpreterConfig** / **setterConfig** forms contain extra fields from time to time. It causes error during saving.

![screenshot from 2018-01-22 16-23-59](https://user-images.githubusercontent.com/8125287/35266084-668d5bf4-0022-11e8-9c4a-207c646d5425.png)

fromColumn: Iternational PID is a checkbox, interpreterConfig should be empty for it (see screenshot) 

The main issue that it doesn't show in which row of the grid that error appeared.

**Comment by dpfaffenbauer** [comment]
can you tell me what you actually did? I just tried to resolve it, but I am not getting the error

**Comment by dpfaffenbauer** [comment]
ping @zavodyanka

**Comment by dpfaffenbauer** [comment]
closed due to inactivity.
