### ISSUE TITLE
AbstractProvider.php has a typo

### ISSUE THREAD

**Issue by josh-palan** [w-vision/ImportDefinitions#5]
https://github.com/w-vision/ImportDefinitions/blob/master/lib/ImportDefinitions/Model/AbstractProvider.php#L223

Should be `            $filterClass = '\ImportDefinitions\Model\Filter\\' . $definition->getFilter();
`

Notice the missing s in definitions. This was causing me errors with my filter classes.

**Comment by dpfaffenbauer** [comment]
thanks
