### ISSUE TITLE
asset_url don't work

### ISSUE THREAD

**Issue by nicogasque** [w-vision/ImportDefinitions#50]
Importing image directly from link doesn't work. interpreter is set to asset_url and path is set as well. 

In my class image is set with the same upload path folder as the asset_url.

When I run the CLI command I have the following error:
08:05:01 ERROR     [import_definition] Exception: unable to resolve asset implementation with type:  in /var/www/pimcore/pimcore/models/Asset.php:477

**Comment by dpfaffenbauer** [comment]
It is working for me, this is how I am using it:

<img width="806" alt="bildschirmfoto 2018-01-30 um 08 19 54" src="https://user-images.githubusercontent.com/5981845/35555207-5be2bf04-0596-11e8-811f-d5c387369194.png">

And this is my data:

```
blub3,blab,bleb,http://lorempixel.com/g/400/203/
```

**Comment by nicogasque** [comment]
Yes, I have the same thing as you, I try with your data and do not work.

Here is my complete error:

:23:53 WARNING   [pimcore] asset with path: /test123/203 doesn't exist [] []
09:23:54 ERROR     [pimcore] Error: Class 'Pimcore\Model\Asset\' not found in /var/www/pimcore/pimcore/lib/Pimcore/Loader/ImplementationLoader/AbstractClassNameLoader.php:43
Stack trace:
#0 /var/www/pimcore/pimcore/lib/Pimcore/Loader/ImplementationLoader/ImplementationLoader.php(106): Pimcore\Loader\ImplementationLoader\AbstractClassNameLoader->build('Pimcore\\Model\\A...', Array)
#1 /var/www/pimcore/pimcore/lib/Pimcore/Model/Factory.php(48): Pimcore\Loader\ImplementationLoader\ImplementationLoader->build('Pimcore\\Model\\A...', Array)
#2 /var/www/pimcore/pimcore/models/Asset.php(471): Pimcore\Model\Factory->build('Pimcore\\Model\\A...')
#3 /var/www/pimcore/vendor/w-vision/import-definitions/src/ImportDefinitionsBundle/Interpreter/AssetUrl.php(65): Pimcore\Model\Asset->save()
#4 /var/www/pimcore/vendor/w-vision/import-definitions/src/ImportDefinitionsBundle/Importer/Importer.php(333): ImportDefinitionsBundle\Interpreter\AssetUrl->interpret(Object(Pimcore\Model\DataObject\Products), 'http://lorempix...', Object(ImportDefinitionsBundle\Model\Mapping), '\xFF\xD8\xFF\xE0\x00\x10JFIF\x00\x01\x01\x01\x00...', Object(ImportDefinitionsBundle\Model\Definition), Array, Array)
#5 /var/www/pimcore/vendor/w-vision/import-definitions/src/ImportDefinitionsBundle/Importer/Importer.php(304): ImportDefinitionsBundle\Importer\Importer->setObjectValue(Object(Pimcore\Model\DataObject\Products), Object(ImportDefinitionsBundle\Model\Mapping), 'http://lorempix...', Array, Object(ImportDefinitionsBundle\Model\Definition), Array)
#6 /var/www/pimcore/vendor/w-vision/import-definitions/src/ImportDefinitionsBundle/Importer/Importer.php(221): ImportDefinitionsBundle\Importer\Importer->importRow(Object(ImportDefinitionsBundle\Model\Definition), Array, Array, NULL)
#7 /var/www/pimcore/vendor/w-vision/import-definitions/src/ImportDefinitionsBundle/Importer/Importer.php(143): ImportDefinitionsBundle\Importer\Importer->runImport(Object(ImportDefinitionsBundle\Model\Definition), Array, NULL, Array)
#8 /var/www/pimcore/vendor/w-vision/import-definitions/src/ImportDefinitionsBundle/Command/ImportCommand.php(96): ImportDefinitionsBundle\Importer\Importer->doImport(Object(ImportDefinitionsBundle\Model\Definition), Array)
#9 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(252): ImportDefinitionsBundle\Command\ImportCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(956): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): Symfony\Component\Console\Application->doRunCommand(Object(ImportDefinitionsBundle\Command\ImportCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(240): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(ImportDefinitionsBundle\Command\ImportCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/pimcore/bin/console(36): Symfony\Component\Console\Application->run()
#16 {main} [] []
09:23:54 ERROR     [import_definition] Exception: unable to resolve asset implementation with type:  in /var/www/pimcore/pimcore/models/Asset.php:477
Stack trace:
#0 /var/www/pimcore/vendor/w-vision/import-definitions/src/ImportDefinitionsBundle/Interpreter/AssetUrl.php(65): Pimcore\Model\Asset->save()
#1 /var/www/pimcore/vendor/w-vision/import-definitions/src/ImportDefinitionsBundle/Importer/Importer.php(333): ImportDefinitionsBundle\Interpreter\AssetUrl->interpret(Object(Pimcore\Model\DataObject\Products), 'http://lorempix...', Object(ImportDefinitionsBundle\Model\Mapping), '\xFF\xD8\xFF\xE0\x00\x10JFIF\x00\x01\x01\x01\x00...', Object(ImportDefinitionsBundle\Model\Definition), Array, Array)
#2 /var/www/pimcore/vendor/w-vision/import-definitions/src/ImportDefinitionsBundle/Importer/Importer.php(304): ImportDefinitionsBundle\Importer\Importer->setObjectValue(Object(Pimcore\Model\DataObject\Products), Object(ImportDefinitionsBundle\Model\Mapping), 'http://lorempix...', Array, Object(ImportDefinitionsBundle\Model\Definition), Array)
#3 /var/www/pimcore/vendor/w-vision/import-definitions/src/ImportDefinitionsBundle/Importer/Importer.php(221): ImportDefinitionsBundle\Importer\Importer->importRow(Object(ImportDefinitionsBundle\Model\Definition), Array, Array, NULL)
#4 /var/www/pimcore/vendor/w-vision/import-definitions/src/ImportDefinitionsBundle/Importer/Importer.php(143): ImportDefinitionsBundle\Importer\Importer->runImport(Object(ImportDefinitionsBundle\Model\Definition), Array, NULL, Array)
#5 /var/www/pimcore/vendor/w-vision/import-definitions/src/ImportDefinitionsBundle/Command/ImportCommand.php(96): ImportDefinitionsBundle\Importer\Importer->doImport(Object(ImportDefinitionsBundle\Model\Definition), Array)
#6 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(252): ImportDefinitionsBundle\Command\ImportCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(956): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(83): Symfony\Component\Console\Application->doRunCommand(Object(ImportDefinitionsBundle\Command\ImportCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(240): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(ImportDefinitionsBundle\Command\ImportCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/pimcore/bin/console(36): Symfony\Component\Console\Application->run()
#13 {main} [] []
 0/1 [>]   0% ( 1 sec/< 1 sec) Error: unable to resolve asset implementation w 1/1 [=] 100% ( 1 sec/1 sec ) Error: unable to resolve asset implementation wi 1/1 [=] 100% ( 1 sec/1 sec ) Error: unable to resolve asset implementation with type:
Import finished!

**Comment by dpfaffenbauer** [comment]
what version of pimcore are you using?

**Comment by nicogasque** [comment]
Pimcore 5

**Comment by dpfaffenbauer** [comment]
Can you please try version 5.1.0, 5.1.1 causes a lot of issues for me.

**Comment by nicogasque** [comment]
So I have to downgrade! 

Do you know if this is going to be fixed in 5.1.1?

Thank you for all your help.

**Comment by dpfaffenbauer** [comment]
The thing is, Pimcore 5.1.1 is unstable, I don't recommend on using it. If this issue still appears in 5.2 or 5.1.2, its gonna get fixed. I had to downgrade some installations cause of instability as well.

The issue you are facing is very strange, the actual error is:

```Error: Class 'Pimcore\Model\Asset' not found in ``` but the class exists in 5.1.1: https://github.com/pimcore/pimcore/blob/v5.1.1/pimcore/models/Asset.php, so something is messed up.

**Comment by nicogasque** [comment]
Thank you very much for your answer, I will use 5.1.0
