### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by nicogasque** [w-vision/ImportDefinitions#52]
Hi,

Column not fount in SQL with localizedfield.

I have many inputs under localizedfields and when a run my definition I have the following error:

----------------------
 1/1 [=] 100% (< 1 sec/< 1 sec) Error: An exception occurred while executing 'SELECT object_localized_10_de.o_id as o_id, `object_localized_10_de`.`o_type` FROM `object_localized_10_de` WHERE (`idmachine~de` = ? AND  object_localized_10_de.o_type IN ('variant','object','folder'))' with params ["250"]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'idmachine~de' in 'where clause'
Import finished!
----------------------

Is ImportDefinition working with multi language?

Thank you for any help.

**Comment by dpfaffenbauer** [comment]
Can I see your definition file?

**Comment by nicogasque** [comment]
Yes, this is an exemple ans I didn't inclus the CSV Exemple

------

{"name":"testimport","provider":"csv","objectPath":"\/Toolbrothers\/Artikel","class":"testimport","configuration":{"csvExample":null,"delimiter":";","enclosure":"\"","csvHeaders":null,"jsonExample":null},"mapping":null,"cleaner":null,"key":"%Text(ID);","filter":null,"renameExistingObjects":false,"relocateExistingObjects":false,"skipNewObjects":false,"skipExistingObjects":false,"runner":null,"createVersion":false,"stopOnException":false,"failureNotificationDocument":null,"successNotificationDocument":null}

**Comment by nicogasque** [comment]
This is the file you have to rename to .json

[import-definition-testimport.txt](https://github.com/w-vision/ImportDefinitions/files/1731328/import-definition-testimport.txt)

Thanks

**Comment by dpfaffenbauer** [comment]
Ok, I see. Primary Key with localized fields is not possible. It doesn't make any sense to have a localized primary identifier.
