### ISSUE TITLE
Create automatically a folder

### ISSUE THREAD

**Issue by nicogasque** [w-vision/ImportDefinitions#53]
Hi,

How can I create automatically a folder in Data Objects using an input name so I can create categories when i'm importing a CSV?

Thanks

**Comment by nicogasque** [comment]
Hi,

Yes I already try this, but this is not working, I don't know why.

in my inportDefinition a set the path to:
/Artikel/%Text(folderName);/

And in my CSV file I have the folderName column but nothing no result.

**Comment by dpfaffenbauer** [comment]
alright, I'll test this and comeback to you.

**Comment by nicogasque** [comment]
Hi,

Sorry I find the Error

Is because the folder name as a dot exemple:
folderName.ID

I import the CSV file from an  impractical system, I can not change anything because it is not an open source and all column as a dot.

**Comment by dpfaffenbauer** [comment]
there could be a solution on my side as well. As it seems like special characters like a dot do make problems, the CSV provider could just transform them to underscores. what do you think?

**Comment by nicogasque** [comment]
Hi,

I cannot change anything from the provider because is not an open source and the company cannot change it for me.

After talking to them the folderName cannot even be in the CSV file, only the folder ID.
The way it work is I have to create the folder manually in the data objects in pimcore with the same ID as the provider ID and somehow to connect the ID to it, so every articles will go to the correct folder.

Is this possible to do it?

Thanks

**Comment by dpfaffenbauer** [comment]
Yeah sure, you can use runner to do that.

But what about the dots inside the column headers?!

**Comment by nicogasque** [comment]
I think for the dot what I will do is, in importDefinions --> Provider settings --> CSV Header: copy the first line from the CSV files en replace all dot with an under line.
So I will have one article which contain the first row line, that ok, I just leave it unpublished, I can live with that.

But I need help to setup the runner to connect ID folder.

**Comment by dpfaffenbauer** [comment]
Runner doc is here: https://github.com/w-vision/ImportDefinitions#runner
