### ISSUE TITLE
Key set

### ISSUE THREAD

**Issue by nicogasque** [w-vision/ImportDefinitions#57]
Hi,

There is an error with the last update.

Not Key set, please check your import-data in /var/www/pimcore/vendor/w-vision/import-definitions/src/ImportDefinitionsBundle/Importer/Importer.php:416

I don't need to set a Key 

How to fix this.

Thanks

**Comment by dpfaffenbauer** [comment]
You need to set a object-key thats a pimcore requirements.

**Comment by nicogasque** [comment]
Hi,

sorry to reopen this, but I think the Key is not working properly, unless I'm doing something wrong.

my Key set is:
%getText(Item_Name);

I have 3 columns in the CSV file the first one in the Header, so I should have two objects but instead I have 5 empty objects created.

**Comment by dpfaffenbauer** [comment]
thats definitely wrong, %getText doesn't exist: https://pimcore.com/docs/5.x/Development_Documentation/Development_Tools_and_Details/Placeholders/Text_Placeholder.html

**Comment by nicogasque** [comment]
Sorry, 
my knowledge is limited.
Whatever I do, I end up with 5 empty articles

That strange because that was working before
%Text(Item_Name);

**Comment by dpfaffenbauer** [comment]
Can you show me your exact confifguration plus your input file, I'll try that as well.

**Comment by nicogasque** [comment]
[Downloads.zip](https://github.com/w-vision/ImportDefinitions/files/1878890/Downloads.zip)

I have exported the definition plus the CSV file.

Thanks for you time.

**Comment by dpfaffenbauer** [comment]
found the issue, your configuration is a bit off. You configured comma as a divider, but your CSV uses a semicolon.

**Comment by dpfaffenbauer** [comment]
BTW: I also implemented a import-definitions extension to be more compatible with Pimcore. Meaning: CoreShop handles prices as integer and float values need to be converted to integers, as well as the storePrice expects either an array with all prices for all stores or a integer value and a store parameter. The configuration for that should look like that:

```
1 => [
                "fromColumn" => "SalesPrice",
                "toColumn" => "storePrice",
                "primaryIdentifier" => FALSE,
                "setter" => "coreshop_store_price",
                "interpreter" => "coreshop_price",
                "interpreterConfig" => [
                    "isFloat" => TRUE
                ],
                "setterConfig" => [
                    "store" => 1
                ]
            ],
```

**Comment by nicogasque** [comment]
Thank you very much for everything
