### ISSUE TITLE
Unable to install the plugin.

### ISSUE THREAD

**Issue by roopak27** [w-vision/ImportDefinitions#58]
I followed the steps described in the installation, updating minimum stability in the composer.json and the resource bundles in AppKernel.php section but system gives error as below.

Problem 1
    - w-vision/import-definitions 2.0.x-dev requires coreshop/resource-bundle ^2.0 -> no matching package found.
    - w-vision/import-definitions 2.0.0-alpha.4 requires coreshop/resource-bundle ^2.0 -> no matching package found.
    - w-vision/import-definitions 2.0.0-alpha.3 requires coreshop/resource-bundle ^2.0-dev@dev -> no matching package found.
    - w-vision/import-definitions 2.0.0-alpha.2 requires coreshop/resource-bundle ^2.0-dev -> no matching package found.
    - w-vision/import-definitions 2.0.0-alpha.1 requires coreshop/resource-bundle ^2.0-dev -> no matching package found.
    - Installation request for w-vision/import-definitions ^2.0-dev -> satisfiable by w-vision/import-definitions[2.0.0-alpha.1, 2.0.0-alpha.2, 2.0.0-alpha.3, 2.0.0-alpha.4, 2.0.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Can you help me solve this?

**Comment by dpfaffenbauer** [comment]
Can you try installing the resource-bundle first and then import-definitions?

```
composer req coreshop/resource-bundle:dev-master
```

**Comment by roopak27** [comment]
@dpfaffenbauer  I executed that cmd but got this error now. 

Problem 1
    - Installation request for coreshop/resource-bundle dev-master -> satisfiable by coreshop/resource-bundle[dev-master].
    - coreshop/resource-bundle dev-master requires coreshop/registry ^2.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.

**Comment by roopak27** [comment]
I have added "minimum-stability": "dev" in the composer.json but its still showing 
The package is not available in a stable-enough version according to your minimum-stability setting
see https://getcomposer.org/doc/04-schema.md#minimum-stability for more details.

How do I check which composer.json its using?

**Comment by dpfaffenbauer** [comment]
Hmmm... I just created a completely new Pimcore 5.2.1 project with a freshly installed composer in version 1.6.3 following command:

```
php composer.phar create-project pimcore/pimcore
```

The I changed the minimum-requirements and prefer-stable settings in the composer.json

```
"minimum-stability": "dev",
 "prefer-stable": true
```

And then required the plugin with:

```
php composer.phar req w-vision/import-definitions:dev-master
```

And it worked....

BTW: I also did following:

```
php composer.phar req coreshop/resource-bundle:dev-master
```

To get the latest version of the resource-bundle, since the alpha.5 has a bug. Beta is on its way.

**Comment by roopak27** [comment]
I used Bitnami Pimcore distribution to install Pimcore. Is it because of that?

**Comment by dpfaffenbauer** [comment]
don't know, never used it.

**Comment by roopak27** [comment]
Hmmm Ok. Thank you. I'll try your way to install Pimcore and see. Thanks again.
