### ISSUE TITLE
Manufacturer and categories to coreshop

### ISSUE THREAD

**Issue by nicogasque** [w-vision/ImportDefinitions#59]
Hi,

I'm trying to import data to coreshope but I cannot assign the manufacturer and categories from my CSV file, the categories remain empty without any error and for the manufacturer I have the following error:
  Invalid href relation fieldname=manufacturer

In my CSV file column I have:

object:/kategorien/Elektrowerkzeuge/Zubehor/Akkus

And 

object:/Hersteller/Bosch/Bosch

In ImportDefinitions I have tried with different setting without any success.

Thanks

**Comment by dpfaffenbauer** [comment]
well, thats an issue with your configuration and not a bug. please only use this issue tracker for bugs.

anyway: check your configuration and check if the classes are correctly configured to allow certain relations.

**Comment by nicogasque** [comment]
when I do CSV import in pimcore the manufacturer and categories works, is still problem with my classes?

**Comment by dpfaffenbauer** [comment]
the pimcore importer works different than import-definitions. I can't even tell you whats wrong, I don't have any context about your setup, import-file nor import-definition configuration.

**Comment by nicogasque** [comment]
ok thanks
