### ISSUE TITLE
How to pass a file for import

### ISSUE THREAD

**Issue by megabait1212** [w-vision/ImportDefinitions#72]
Hi, could explain how to upload/pass a file for import? I read your documentation but didn't find how to do it. 
I want to create a few import definitions for each supplier and then import stock by cron. Thank you

**Comment by dpfaffenbauer** [comment]
CLI, like this:

```bin/console import-definitions:import -d 1 -p "{\"file\":\"PATH/TO/FILE.csv\"}"```

**Comment by megabait1212** [comment]
Thank you
