### ISSUE TITLE
Bug: ucfisrt missing on some class call.

### ISSUE THREAD

**Issue by Yivan** [w-vision/ImportDefinitions#8]
Hello,

I tested your plugin ImportDefinitions, and it is really great, well thinked, good coding quality and nice features : )
Thanks a lot for sharing it.

I got some problem to make it work (on linux so case is sensitive), here are the changes i had to do to make it work, i think you could changed it on the source code so other users don't get any problem:

There is ucfirst needed on the following lines:

https://github.com/w-vision/ImportDefinitions/blob/master/lib/ImportDefinitions/Model/AbstractProvider.php#L347
https://github.com/w-vision/ImportDefinitions/blob/master/lib/ImportDefinitions/Model/AbstractProvider.php#L348
https://github.com/w-vision/ImportDefinitions/blob/master/lib/ImportDefinitions/Model/Setter/Objectbrick.php#L56
https://github.com/w-vision/ImportDefinitions/blob/master/lib/ImportDefinitions/Model/Setter/Objectbrick.php#L56

I tested only with normal class with Objectbricks, but maybe the same problem is on some other files.

Thanks a lot.

**Comment by Yivan** [comment]
I was testing fieldcollections, it seems it is missing ucfirst here:
https://github.com/w-vision/ImportDefinitions/blob/master/lib/ImportDefinitions/Model/Setter/Fieldcollection.php#L44

**Comment by dpfaffenbauer** [comment]
Thanks a lot, I really appreciate your compliment and I am very happy you are using the plugin :)

Seems you are right.
