### ISSUE TITLE
[UX] improve command line experience

### ISSUE THREAD

**Issue by dkarlovi** [w-vision/ImportDefinitions#80]
Here are two simple ideas which might significantly improve the developer/user experience:

1. allow to also set definition by name, like `--definition ProductTree` instead of just `--definition 1`, much more readable
2. allow to pass only the source file as a separate param, not (only) via `--params`, for example `--source path/to/file.csv`, reason is your shell completion works again and it's easier than constructing the JSON params

**Comment by dpfaffenbauer** [comment]
1. Yes, agree with your. Would you create a PR for that?
2. Cannot agree with you 100%. There is a reason for the JSON, not every provider has a input source, like SQL.

**Comment by dkarlovi** [comment]
1. Sure
2. It would work for providers which have a file-based input, so we can make it `--source-file` or similar. It would just be a shortcut to the existing functionality, if a file is not expected, it doesn't work.

**Comment by dpfaffenbauer** [comment]
2. Yes, I already thought about it. But didn't implement it cause its not 100% consistent. CSV Provider for example also takes arguments like `offset` and `limit` to only import a certain subset of the whole file.... So it would be a mix and match between json params and cli arguments.

**Comment by dpfaffenbauer** [comment]
related to https://github.com/w-vision/ImportDefinitions/issues/90 somehow

**Comment by dpfaffenbauer** [comment]
I will close this for now, as there will be no proper solution. Every provider could have different parameters... thats why it is a json.
