### ISSUE TITLE
[Bug] seeing items from the classification store twice in the UI

### ISSUE THREAD

**Issue by dkarlovi** [w-vision/ImportDefinitions#83]
Currently, I'm seeing properties from the classification store twice in definition edit form. All the properties are listed, then listed again.

I've assumed it was locale-related (since I had two locales enabled), but it stayed twice even after adding the third locale so it's probably unrelated.

**Comment by dpfaffenbauer** [comment]
I pushed a fix for that, can you check pls?

**Comment by dkarlovi** [comment]
This works correctly now. :+1: 

BTW looking at the new solution, the question is if you need the `Field` config anymore, since you're mapping to a known field already?

Example: my classification store field is called `MyFeat` ,

I end up with this:

```
            [
                "fromColumn" => "seal",
                "toColumn" => "classificationstore~MyFeat~6~2",
                "primaryIdentifier" => FALSE,
                "setter" => "classificationstore",
                "setterConfig" => [
                    "field" => "MyFeat",
                    "keyConfig" => 6,
                    "groupConfig" => 2
                ]
            ],
```

This would only be required if you had two separate links to the same CS from different fields, I guess? Seems like a corner case, might want to add a dropdown with a default here instead of an input.

**Comment by dpfaffenbauer** [comment]
Guess you are right... But I am not 100% sure tbh. Lets keep it for know to be on the safe side
