### ISSUE TITLE
nested interpreter destroing container

### ISSUE THREAD

**Issue by wpeisert** [w-vision/ImportDefinitions#85]
While running an import definition:
$ bin/console import-definitions:import -d 1 -p "{\"file\":\"path/to/file\"}" --env=dev

I got error:
In ServiceRegistry.php line 64:
   Import Definition Interpreters needs to be an object, boolean given.  

Debugging shows that it is when NestedInterpreter is being registered (got true instead of service).
This is because of the following code from the container:
`
if (isset($this->privates['import_definition.interpreter.nested'])) {
    return $this->privates['import_definition.interpreter.nested'];
}
`
So, maybe it is a Symfony error?

Workaround is to make import_definition.interpreter.nested service public.

**Comment by dpfaffenbauer** [comment]
what? I don't quite get it.

**Comment by wpeisert** [comment]
ImportCommand::execute(), line no. 102 is:
$this->getContainer()->get('import_definition.importer')->doImport($definition, json_decode($params, true));
Then there is a call: ServiceRegistry::register('nested, true) - this results in the error.

**Comment by dpfaffenbauer** [comment]
yes, but it still doesn't make sense to me. 

1. it works for me
2. the service is private, yes, but it is directly injected into the ServiceRegistry, therefore it's fine to be private.

**Comment by wpeisert** [comment]
For me it also looks fine. But it does not work for me and I do not understand why.

**Comment by dpfaffenbauer** [comment]
Can you give me your composer.lock file and I check.

**Comment by dpfaffenbauer** [comment]
tried to reproduce your issue, no chance... something is different in your setup.

**Comment by dpfaffenbauer** [comment]
ok, you are not using a stable version of symfony, and thats the issue. They changed something, I don't know what, but it it doesn't create private services anymore. Please always use stable versions if possible. Add this to your composer file:

```
    "minimum-stability": "dev",
    "prefer-stable": true
```
