### ISSUE TITLE
[UX] Normalize (asset?) paths in config

### ISSUE THREAD

**Issue by dkarlovi** [w-vision/ImportDefinitions#88]
When you get the chance to enter a path, the component should ensure it's normalized. Example, Asset URL interpeter.

This means:

1. must have leading slash
2. must not have trailing slash
3. must not have double slashes

etc

This would apply if using hardcoded values and not placeholders (from that side), since placeholders might generate proper values by themselves.

**Comment by dpfaffenbauer** [comment]
closed for not having any activity in about a year now... If still needed, let me know.
