### ISSUE TITLE
Improvement: install/unsinstall and db table name.

### ISSUE THREAD

**Issue by Yivan** [w-vision/ImportDefinitions#9]
I think install (in the Pimcore GUI) could send a nicer message than "true" (like: "Installation has been done").

There is no uninstall script, actually it just send "true" popin but do nothning.
Maybe it could send a nice message, and make some clean up. From what i have understand it could be:
- delete the table `importdefinitions_log`
- delete the file `/var/config/importdefintions.php`
- delete the directory `/plugins/ImportDefinitions`

By the way, maybe prefix the table name with "plugins_" (so it will be `plugins_importdefinitions_log`) could be better (it seems to be the Pimcore way good pratice, and will ensure no collision later on future Pimcore updates wich use the same name).

Thanks!

**Comment by dpfaffenbauer** [comment]
You are right.

But:

 - I would no delete the importdefinitions file: when somebody uninstalls the plugin by accident, all the configurations are gone...
 - I would not delete the plugins folder. That doesn't feel like a good pimcore practice.
 - Table Name: well, yeah. Maybe you are right, but I don't think it's necessary

**Comment by Yivan** [comment]
Concerning you three point:
- ok i understand and your are right
- i was thinking uninstall mean deleting the files in plugin folder, but if usually it is left so yes it is better to not delete it
- or table name ok, as it can involve some  backward compatibility problem (or you have to make a post update script). But usualy i prefer to have table prefixed with plugins (some of the pimcore team are made like this) so wehn you are looking table on the database you know it is a table from plugin and not from the core pimcore.

Thanks!
