### ISSUE TITLE
Add new runner interface to decide if object should be saved or not in importer

### ISSUE THREAD

**Issue by caupo-roy** [w-vision/ImportDefinitions#95]
I would like to suggest adding a new Runner interface with a method shouldSaveObject. If the runner implements this interface then this method should be called before $object->save() in the Importer. 

Our use case is that we only want to save the object when there are actual changes to the data. We get a dump of all products from the customers "rather dumb" ERP system daily. Only very few products will have changes from one day to the other. We do not want a new version of the object every day. We only want a new version (to save the object) when there are actual changes in the data for that particular product.

By implementing the SetterRunnerInterface our runner can decide if the object should be saved. The new Interface would also allow the runner to prevent the object save.

**Comment by dpfaffenbauer** [comment]
PR for that is very much welcome :)

**Comment by caupo-roy** [comment]
Would it be good form to include a general/sample runner implementing the interface or should runners be implemented outside the bundle?

**Comment by dpfaffenbauer** [comment]
That’s documentation. Having a sample in the  bundle itself wouldn’t help anybody

**Comment by dpfaffenbauer** [comment]
done
